### ISSUE TITLE
mod_md in httpd@2.4.63 fails to compile with openssl@1.0.2 - changes of mod_md@2.4.31 missing in upstream httpd project?

### ISSUE THREAD

**Issue by frgreiner** [icing/mod_md#372]
I encountered Errors when compiling apache2 Version 2.4.62 on an old container with OpenSSL 1.0.2k (it fails compiling mod_md)

```
[...]
Building shared: mod_md.la
[...]
/httpd-2.4.62/modules/mappers -prefer-pic -c md_crypt.c && touch md_crypt.slo
md_crypt.c: In function 'md_pkey_get_rsa_e64':
md_crypt.c:982:5: warning: implicit declaration of function 'EVP_PKEY_get0_RSA' [-Wimplicit-function-declaration]
     const RSA *rsa = EVP_PKEY_get0_RSA(pkey->pkey);
     ^
md_crypt.c:982:22: warning: initialization makes pointer from integer without a cast [enabled by default]
     const RSA *rsa = EVP_PKEY_get0_RSA(pkey->pkey);
                      ^
md_crypt.c: In function 'md_pkey_get_rsa_n64':
md_crypt.c:1002:22: warning: initialization makes pointer from integer without a cast [enabled by default]
     const RSA *rsa = EVP_PKEY_get0_RSA(pkey->pkey);
                      ^
md_crypt.c: In function 'md_cert_get_ct_scts':
md_crypt.c:2071:5: error: unknown type name 'SCT'
     SCT *sct_handle;
     ^
In file included from /usr/include/openssl/crypto.h:129:0,
                 from /usr/include/openssl/bio.h:69,
                 from /usr/include/openssl/err.h:124,
                 from md_crypt.c:28:
md_crypt.c:2084:29: error: 'SCT' undeclared (first use in this function)
                sct_handle = sk_SCT_value(sct_list, i);
                             ^
md_crypt.c:2084:29: note: each undeclared identifier is reported only once for each function it appears in
md_crypt.c:2084:29: error: expected expression before ')' token
                sct_handle = sk_SCT_value(sct_list, i);
                             ^
md_crypt.c:2087:21: warning: implicit declaration of function 'SCT_get_version' [-Wimplicit-function-declaration]
                     sct->version = SCT_get_version(sct_handle);
                     ^
md_crypt.c:2088:21: warning: implicit declaration of function 'SCT_get_timestamp' [-Wimplicit-function-declaration]
                     sct->timestamp = apr_time_from_msec(SCT_get_timestamp(sct_handle));
                     ^
md_crypt.c:2089:21: warning: implicit declaration of function 'SCT_get0_log_id' [-Wimplicit-function-declaration]
                     len = SCT_get0_log_id(sct_handle, (unsigned char**)&data);
                     ^
md_crypt.c:2091:21: warning: implicit declaration of function 'SCT_get_signature_nid' [-Wimplicit-function-declaration]
                     sct->signature_type_nid = SCT_get_signature_nid(sct_handle);
                     ^
md_crypt.c:2092:21: warning: implicit declaration of function 'SCT_get0_signature' [-Wimplicit-function-declaration]
                     len = SCT_get0_signature(sct_handle,  (unsigned char**)&data);
                     ^
make[4]: *** [md_crypt.slo] Error 1
[...]
```

After a short Research I found the following Thread describing a similar Issue:
https://lists.apache.org/thread/7kp2vvop9zfr4709q3w75qofygfkqoby

Reading the Changelog of Version 2.4.63 "Restore compatibility with OpenSSL < 1.1." I assumed the Compatibility would be restored and the provided Patches got applied.

After updating the source files to 2.4.63 I still encounter the same Error.

When comparing the Tags of httpd sources on GitHub
https://github.com/apache/httpd/compare/2.4.62...2.4.63
I could not find any of the changes mentioned in the above Thread regarding the compatibility to OpenSSL.

When Comparing the contents of files in
https://github.com/apache/httpd/tree/2.4.63/modules/md
and
https://github.com/icing/mod_md/tree/v2.4.31/src
it seems to me like some of the changes to mod_md (including the Compatibility to OpenSSL < 1.1) are missing although the [changelog of httpd@2.4.63](https://downloads.apache.org/httpd/CHANGES_2.4) states that mod_md has been updated to 2.4.31

**Comment by icing** [comment]
It seems the [fix for this](https://svn.apache.org/viewvc?view=revision&revision=1913837) in Apache subversion trunk was never backported to the 2.4.x branch. The fix is here in this repository. This is unfortunate. 

The only thing I can do is make sure that the next httpd release gets the changes.

Can you compile the module from here for your work?

**Comment by frgreiner** [comment]
Thanks for the Confirmation! Mainly I just wanted to point out, that the Changelog might be misleading. Although hopefully the majority is using newer openssl versions.

I'll be looking forward for the next httpd release, thank you!

Until then, I will try to compile httpd with mod_md sources from here.
